# Generated by Django 3.1.3 on 2020-12-08 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('text', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='img', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='nombre',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='Name Error', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=100)),
                ('number', models.IntegerField()),
                ('description', models.TextField(max_length=400)),
                ('script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.script')),
            ],
        ),
    ]
