# Generated by Django 3.1.3 on 2020-12-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201208_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='script',
        ),
        migrations.AddField(
            model_name='script',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
