# Generated by Django 3.1.3 on 2020-12-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201208_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
