# Generated by Django 3.1.3 on 2020-12-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201208_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Image'),
        ),
    ]
