# Generated by Django 2.2.17 on 2020-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201208_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='Category',
        ),
        migrations.AddField(
            model_name='script',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Category'),
        ),
    ]
