# Generated by Django 3.1.2 on 2020-12-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201209_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='number',
        ),
    ]
