# Generated by Django 3.1.3 on 2020-12-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_script_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='script',
            name='user',
        ),
    ]
